name: Build and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
          include-prerelease: false

      - name: Build solution and generate NuGet package
        run: dotnet build -c Release

      - name: Run Nuget pack
        run: dotnet pack --configuration Release /p:NuspecFile=../../SdkGenerator.nuspec

      - name: Push generated package to NuGet registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}